# @file
# .travis.yml - PKP Plugins Integration

dist: focal
os: linux
language: php

addons:
  chrome: beta
  postgresql: "9.5"
  apt:
    update: true
    packages:
      - libvulkan1
      - libu2f-udev

sudo: required

php:
  - 8.1.0
  - 8.2.0
env:
  - APPLICATION=ojs BRANCH=main TEST=mysql
  - APPLICATION=ojs BRANCH=main TEST=pgsql

install:
  - php --version | grep "PHP 8.2" && sudo apt-get install libonig5
  # Prepare OJS environment
  - git clone -b ${BRANCH} https://github.com/pkp/${APPLICATION} ~/${APPLICATION}
  - cd ~/${APPLICATION}
  - git submodule update --init --recursive
  - source lib/pkp/tools/travis/prepare-tests.sh
  - lib/pkp/tools/travis/prepare-webserver.sh
  # Build/install dependencies
  - lib/pkp/tools/travis/install-composer-dependencies.sh
  - npm i g -npm && npm install && npm run build
  - ln -s ${TRAVIS_BUILD_DIR} ~/${APPLICATION}/plugins/themes/pragma
  # Install OJS & prep data environment
  - $(npm bin)/cypress run --spec "cypress/tests/data/10-ApplicationSetup/*.cy.js,cypress/tests/data/60-content/VkarbasizaedSubmission.cy.js"

script:
  - $(npm bin)/cypress run --config specPattern=plugins/themes/pragma/cypress/tests/functional

after_failure:
  - cat error.log
  - sudo apt-get install sharutils
  - tar cz cypress/screenshots | uuencode /dev/stdout
